# Set the maximum line length to 79.
line-length = 79

[lint]
# Add the `line-too-long` rule to the enforced rule set.
extend-select = ["E501"]

# [lint.per-file-ignores]
# "/path/to/file/that/should/ignore/E501" = ["E501"]
